/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import Connection.ConnectDB;
import Controller.ControllerHome;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shintadl
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    ControllerHome cH;
    DefaultTableModel model;
    Connection connection;
    public HomePage() {
        initComponents();
        cH = new ControllerHome(this);
        cH.showFoodTable();
        this.connection = ConnectDB.getCon();
    }
    
    ViewFood jviewRecipe = new ViewFood(); // make a object from class ViewFood view frame 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFood = new javax.swing.JTable();
        jbSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTfSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 240, 205));

        jTableFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFood.setColumnSelectionAllowed(true);
        jTableFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFoodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFood);
        jTableFood.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jbSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Search.png"))); // NOI18N
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Log out.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTfSearch.setBorder(null);
        jTfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfSearchActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(233, 236, 217));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(164, 51, 13));
        jLabel1.setText("Home Page");

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nia\\Downloads\\Logo\\Add.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/LogoBrownonly.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(438, 438, 438))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfSearchActionPerformed

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        // TODO add your handling code here:
        cH.showSearchFood();
    }//GEN-LAST:event_jbSearchActionPerformed
    
    private void jTableFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFoodMouseClicked
        // TODO add your handling code here:
        // For making the viewFood page show the data that necessary based on the information from homepage view
        int row = jTableFood.getSelectedRow(); // getting which row that have been clicked (jTableFood : from the table list in homepage view)
        int col = jTableFood.getSelectedColumn(); // getting which col that have been clicked (same as row)
        String foodName = null; // foodName for saving the information for the foodName attribute must be set null imposible if it don't
        String foodDesc = null;// foodDesc for saving the information for the foodDesc attribute (same as foodName)
        
        
        if (row >= 0 && col >= 0) { // checking if the row and col that've been clicked is empty
            foodName = (String) jTableFood.getValueAt(row, col); // getting value based on row and col on line 136,137
          
            try { // for connecting to data base 
                // TODO add your handling code here:
                Statement st = connection.createStatement(); // use statement as default for connection keep in st object
                ResultSet rs = st.executeQuery("SELECT foodDesc FROM food WHERE foodName LIKE '%"+foodName+"%'"); // connect to data base for foodDesc save it to rs object
                if (rs.next()){ // for getting and checking if the data have been found
                    foodDesc = rs.getString(1); // keep the data from line 146 to foodDesc object
                }else { // for safety purposes 
                    foodDesc = "failed"; // if didn't find just print it failed 
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(ViewFood.class.getName()).log(Level.SEVERE, null, ex);
            }
            jviewRecipe.setVisible(true); // getting the ViewFood class visible you can see in line 40 HomePage view
            jviewRecipe.pack(); // getting the necessary stuff for preparing the viewFood frame
            jviewRecipe.setLocationRelativeTo(null); // set the setLocationRelative to null
            jviewRecipe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // use JFrame.DISPOSE_ON_CLOSE default for making a new frame
            
            jviewRecipe.jfoodName.setText(foodName); // set jfoodName in ViewRecipe in use object foodName
            jviewRecipe.jfoodDesc.setText(foodDesc); // set jfoodDesc in ViewRecipe in use object foodDesc
            
            this.dispose(); // close HomePage frame 
            
        }
        
        
        
    }//GEN-LAST:event_jTableFoodMouseClicked
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        LoginForm lf = new LoginForm();
        
        this.dispose();
        lf.setVisible(true);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AddFood Af = new AddFood();
        Af.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableFood;
    public javax.swing.JTextField jTfSearch;
    private javax.swing.JButton jbSearch;
    // End of variables declaration//GEN-END:variables
    
    public JTextField getTfSearch() {
        return jTfSearch;
    }
    
    public void setTfSeach(JTextField jTfSearch) {
        this.jTfSearch = jTfSearch;
    }
    
    public JButton getBSearch() {
        return jbSearch;
    }
    
    public void setBSearch(JButton jbSearch) {
        this.jbSearch = jbSearch;
    }
    
    public JTable getTableFood() {
        
        return jTableFood;
    }
    
    public void setTableFood(JTable jTableFood) {
        this.jTableFood = jTableFood;
    }

}
